version: '3.7'
services:
    mirakurun:
        build:
            context: docker
        cap_add:
            - SYS_ADMIN
            - SYS_NICE
        ports:
            - "40772:40772"
            - "9229:9229"
        volumes:
            - ./conf:/app-config
            - ./data:/app-data
        environment:
            TZ: "Asia/Tokyo"
        devices:
            - /dev/bus:/dev/bus
            - /dev/px4video0:/dev/px4video0
            - /dev/px4video1:/dev/px4video1
            - /dev/px4video2:/dev/px4video2
            - /dev/px4video3:/dev/px4video3
        restart: always
        logging:
            driver: json-file
            options:
                max-file: "1"
                max-size: 10m
        user: "1000:1000"


